site_name: Pruebas
site_url: https://bpaterna.github.io/pruebas/
site_author: Bego√±a Paterna
theme:
  name: material
  language: es
  palette:
    scheme: default
    primary: pink
  features:
    - navigation.instant
    - navigation.top
    - search.highlight
    - search.suggest
    - content.tabs.link
nav:
  - Inicio: index.md
  - Unidad 1: unidad1.md
  - Unidad 2: unidad2.md
  - Unidad 3: unidad3.md
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
plugins:
  - with-pdf:
      output_path: pdf/pruebas8.pdf
      cover: true
      toc_title: "Pruebas"
      exclude_pages:
        - "index.md"
        - "unidad2.md"
