site_name: Pruebas
site_url: https://bpaterna.github.io/pruebas/
theme:
  name: material
  language: es
  palette:
    scheme: default
    primary: pink
  features:
    - navigation.instant
    - navigation.top
    - search.highlight
    - search.suggest
    - content.tabs.link

# NavegaciÃ³n del sitio
nav:
  - Inicio: index.md
  - Unidad 1: unidad1.md
  - Unidad 2: unidad2.md
  - ðŸ“¥ Descargar PDF: pdf/pruebas3.pdf

# Plugins  
plugins:
  - with-pdf:
      output_path: pdf/pruebas3.pdf
      cover: true
      cover_title: "Materiales de pruebas"
      cover_subtitle: "Curso 2025-2026"
      author: "Tu Nombre"
      toc_title: "Pruebas"
      exclude_pages:
        - index.md

# Extensiones Markdown
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed

# Footer y enlaces sociales
extra:
  social:
    - icon: material/file-pdf-box
      link: pdf/pruebas3.pdf
      name: Descargar PDF
  copyright: >
    Â© 2025 Tu Nombre â€” Publicado bajo
    <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank">Licencia CC BY-SA 4.0</a>.
  fecha_generacion: !!python/object/apply:datetime.date.today []
